---
- name: Install PostgreSQL
  apt: name={{ item }} update_cache=true state=installed
  with_items:
    - postgresql
    - postgresql-contrib
    - libpq-dev
    - python-psycopg2
  tags: packages

- name: Ensure the PostgreSQL service is running
  service: name=postgresql state=started enabled=yes

- name: Ensure database is created
  become_user: postgres
  postgresql_db: name={{ app_db_name }}
             encoding='UTF-8'
             lc_collate='C.UTF-8'
             lc_ctype='C.UTF-8'
             template='template0'
             state=present

- name: Ensure user has access to the database
  become_user: postgres
  postgresql_user: db={{ app_db_name }}
               name={{ app_user }}
               password={{ app_db_pass }}
               priv=ALL
               state=present

- name: Ensure user does not have unnecessary privileges
  become_user: postgres
  postgresql_user: name={{ app_user }}
               role_attr_flags=NOSUPERUSER,NOCREATEDB
               state=present
