apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-conf
data:
  site.conf: |
    upstream website {
        server localhost:8080;
    }

    server {
        listen 80;
        server_name _;
        location /static {
            alias /usr/share/nginx/html;
        }

       location / {
            proxy_pass http://website;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
         }
    }
