apiVersion: apps/v1
kind: Deployment
metadata:
  name: fk-frontend-prod
spec:
  selector:
    matchLabels:
      app: fk-frontend-prod
  minReadySeconds: 5
  template:
    metadata:
      labels:
        app: fk-frontend-prod
    spec:
      containers:
      - name: fk-frontend-prod
        image: frikanalen/frontend:latest
        imagePullPolicy: Always
        ports:
          - name: web
            containerPort: 3000
        envFrom:
          - configMapRef:
              name: frontend-prod-config
