apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: fill-next-weeks-agenda
spec:
  schedule: "00 22 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: django
            image: frikanalen/django-backend
            args:
              - ./manage.py
              - fill_next_weeks_agenda
              - -v
              - '2'
            env:
              - name: DJANGO_SETTINGS_MODULE
                value: fkweb.settings.production
              - name: DATABASE_HOST
                value: database-api
              - name: DATABASE_USER
                value: fkweb
              - name: DATABASE_NAME
                value: fkweb
              - name: ALLOWED_HOSTS
                value: frikanalen.no,fk.dev.local,forrige.frikanalen.no
              - name: SMTP_SERVER
                value: smtp.uio.no
              - name: SECRET_KEY
                valueFrom:
                   secretKeyRef:
                      name: django-secret-key
                      key: SECRET_KEY
              - name: DATABASE_PASS
                valueFrom:
                   secretKeyRef:
                      name: database-api-secret
                      key: POSTGRES_PASSWORD
          restartPolicy: OnFailure
