---
- name: Install certbot
  apt: name=certbot
  when: ansible_distribution_release != 'jessie'

- name: Install certbot (jessie)
  apt: name=certbot default_release='jessie-backports'
  when: ansible_distribution_release == 'jessie'

- name: Ensure certbot well-known path exists
  file:
    path: "/srv/certbot/.well-known"
    state: directory

- name: Check if we already have cert
  stat:
    path: /etc/letsencrypt/live/{{ domain }}/fullchain.pem
  register: cert

- name: Ensure any pending nginx reload happens immediately
  meta: flush_handlers
  when: cert.stat.exists == False

- name: Obtain initial cert
  command: certbot certonly --non-interactive --webroot
    -d {{ domain }} --email={{ email }} --agree-tos
    -w /srv/certbot --post-hook 'systemctl reload nginx'
  when: cert.stat.exists == False

- name: Enable certbot timer
  systemd:
    name: certbot.timer
    state: started
    enabled: True

#- name: Strong DH params
#  command: openssl dhparam -out /etc/ssl/certs/dhparam.pem 2048
#           creates=/etc/ssl/certs/dhparam.pem
