---
- name: Install packages
  apt: name={{item}}
  with_items:
    - nginx

- name: Ensure default nginx server is not present
  file:
    path: /etc/nginx/sites-enabled/default
    state: absent
  notify: reload nginx

- name: Check if we have cert
  stat:
    path: /etc/letsencrypt/live/{{ domain }}/fullchain.pem
  register: letsencrypt_cert

- name: Check if we have nginx sites
  find:
    paths: /etc/nginx/sites-enabled/
  register: nginx_sites

- import_tasks: letsencrypt.yml
  when: nginx_sites.matched > 0
