apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: cors
  namespace: default
spec:
  headers:
    customResponseHeaders:
      Access-Control-Allow-Origin: "*"
      Access-Control-Allow-Headers: "Content-Type, Access-Control-Allow-Headers, Authorization, X-Requested-With"
      Access-Control-Allow-Methods: "POST"
---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: strip-atem-prefix
  namespace: default
spec:
  stripPrefix:
    prefixes:
      - /playout/atem
---
kind: IngressRoute
apiVersion: traefik.containo.us/v1alpha1
metadata:
  name: atem-control
  namespace: default
spec:
  entryPoints: 
    - websecure
  routes:
  - match: Host(`frikanalen.no`) && PathPrefix(`/playout/atem/`)
    kind: Rule
    middlewares:
      - name: strip-atem-prefix
        namespace: default
      - name: cors
        namespace: default
    services:
    - kind: Service
      name: atem-control
      scheme: http
      port: 80
  tls:
    certResolver: default
