apiVersion: apps/v1
kind: Deployment
metadata:
  name: fk-on-air-graphics
spec:
  selector:
    matchLabels:
      app: fk-on-air-graphics
  minReadySeconds: 5
  template:
    metadata:
      labels:
        app: fk-on-air-graphics
    spec:
      containers:
      - name: fk-on-air-graphics
        image: frikanalen/on-air-graphics:latest
        imagePullPolicy: Always
        ports:
          - name: web
            containerPort: 80
