kind: Service
apiVersion: v1
metadata:
  name: upload-receiver
spec:
  type: ClusterIP
  selector:
    app: upload-receiver
  ports:
    - protocol: TCP
      port: 1080
      name: web
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: upload-receiver
spec:
  selector:
    matchLabels:
      app: upload-receiver
  replicas: 1
  minReadySeconds: 5
  template:
    metadata:
      labels:
        app: upload-receiver
    spec:
      containers:
      - name: upload-receiver
        image: frikanalen/upload-receiver:latest
        imagePullPolicy: Always
        ports:
          - name: web
            containerPort: 1080
        env:
          - name: AWS_ACCESS_KEY_ID
            valueFrom:
              secretKeyRef:
                name: upload-receiver
                key: AWS_ACCESS_KEY_ID
          - name: AWS_SECRET_ACCESS_KEY
            valueFrom:
              secretKeyRef:
                name: upload-receiver
                key: AWS_SECRET_ACCESS_KEY
          - name: AWS_REGION
            valueFrom:
              secretKeyRef:
                name: upload-receiver
                key: AWS_REGION
          - name: FK_TOKEN
            valueFrom:
              secretKeyRef:
                name: upload-receiver
                key: FK_TOKEN
          - name: FK_API
            value: http://fk.dev.local/api
